# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master
- release

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.Full.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetVersionSpec: '5.x.x'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet $(nugetVersionSpec)'
  inputs:
    versionSpec: '$(nugetVersionSpec)'

- powershell: .paket\paket.exe restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU" /p:MDIXVersion=$(mdixVersion).$(Build.BuildID) /p:MDIXColorsVersion=$(mdixColorsVersion).$(Build.BuildID) /p:MDIXMahAppsVersion=$(mdixMahappsVersion).$(Build.BuildID)'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: Windows Application Driver@0
  displayName: 'Start WinAppDriver'
  inputs:
    OperationType: 'Start'
    AgentResolution: '1080p'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: DotNetCoreCLI@2
  displayName: 'UI Tests'
  inputs:
    command: test
    projects: '**/*.UITests'
    arguments: '--configuration $(buildConfiguration) --no-build'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: Windows Application Driver@0
  displayName: 'Stop WinAppDriver'
  inputs:
    OperationType: 'Stop'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: PublishPipelineArtifact@0
  name: "PublishUITestsScreenshots"
  inputs:
    artifactName: 'Screenshots'
    targetPath: 'MaterialDesignThemes.UITests/bin/$(buildConfiguration)/netcoreapp3.1/Screenshots'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: PowerShell@2
  displayName: "Build NuGets"
  inputs: 
    filePath: 'Scripts\\BuildNugets.ps1'
    arguments: '-MDIXVersion $(mdixVersion)-ci$(Build.BuildId) -MDIXMahAppsVersion $(mdixMahappsVersion)-ci$(Build.BuildId) -MDIXColorsVersion $(mdixColorsVersion)-ci$(Build.BuildId)'

- task: PublishPipelineArtifact@0
  name: "PublishDemoApp"
  inputs:
    artifactName: 'DemoApp'
    targetPath: 'MainDemo.Wpf/bin/$(buildConfiguration)'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesign"
  inputs:
    artifactName: 'MDIX'
    targetPath: 'MaterialDesignThemes.$(mdixVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignColors"
  inputs:
    artifactName: 'MDIX.Colors'
    targetPath: 'MaterialDesignColors.$(mdixColorsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignMahApps"
  inputs:
    artifactName: 'MDIX.MahApps'
    targetPath: 'MaterialDesignThemes.MahApps.$(mdixMahappsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishScript"
  inputs:
    artifactName: 'Script'
    targetPath: 'Scripts\\UpdateNugets.ps1'